[General]
  snippetfile = "/home/panxiangrong/.config/pet/snippet.toml"
  editor = "vim"
  column = 40
  selectcmd = "fzf"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = "ded100e39dea83df514c3300107748b124194138"
  gist_id = "ae8023245efe6b5a4d261445a503e175"
  public = false
  auto_sync = false
